name: VarScript
description: More more more in-game scripting!
authors: [DPOH-VAR, MYXOMOPX]
main: me.dpohvar.varscript.VarScript
version: 0.5.5
softdepend: [PowerNBT]
commands:
    "task":
        description: manage tasks
        usage: /task <name> <operation>
        permission: varscript.command.task
    "scheduler":
        description: manage scheduler
        usage: /scheduler [enable|disable|reload]
        permission: varscript.command.scheduler
        aliases: ">s"
    "js":
        description: manage javascript
        usage: /js <varscript>
        permission: varscript.command.js
    "vs>":
        description: run varscript code
        usage: /vs> <varscript>
        permission: varscript.command.vsrun
        aliases: ">"
    "js>":
        description: run javascript code
        usage: /js <javascript>
        permission: varscript.command.jsrun
    "script>":
        description: run javascript code
        usage: /script> <Language> <script>
        permission: varscript.command.script
        aliases: "->"
    "script>file":
        description: run javascript code
        usage: /script> <Language> <script>
        permission: varscript.command.script
        aliases: "->f"
    "js>file":
        description: run javascript file
        usage: /js>file <filename>
        permission: varscript.command.jsfile
        aliases: "js>f"
    "vs>tag":
        description: list commands for tag or list all tags
        usage: /vs>tag [tag]
        permission: varscript.command.jsfile
        aliases: ">t"
    "vs>cmd":
        description: view help about command
        usage: /vs>cmd [command]
        permission: varscript.command.jsfile
        aliases: ">c"